import { NextResponse } from 'next/server';

export async function POST() {
  return NextResponse.json({ message: 'Email service is currently disabled.' }, { status: 200 });
}

/*
import { prisma } from '@/lib/db';
import { generateQuotationPDF } from '@/lib/pdf';
import nodemailer from 'nodemailer';

export async function POST_DISABLED(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const quotation = await prisma.quotation.findUnique({
      where: { id },
      include: {
        customer: true,
        assessment: true,
        items: true,
      },
    });

    if (!quotation || !quotation.customer) {
      return NextResponse.json({ error: 'Quotation or customer not found' }, { status: 404 });
    }

    // 1. Generate PDF buffer
    const pdfBuffer = await generateQuotationPDF(quotation);

    // 2. Configure Nodemailer Transporter
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_PORT === '465',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASSWORD,
      },
    });

    const companyName = 'StartupFlora';
    const clientName = quotation.customer.name;
    const clientEmail = quotation.customer.email;

    const mailOptions = {
      from: `"${companyName}" <${process.env.SMTP_USER}>`,
      to: clientEmail,
      subject: `Your StartupFlora Digital Marketing Strategy Proposal & Quotation - #${quotation.quotationNumber}`,
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #334155; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; padding: 20px; border-radius: 8px;">
          <h2 style="color: #1a7a3e; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">StartupFlora Digital Marketing Proposal & Quotation</h2>
          <p>Dear ${clientName},</p>
          <p>Thank you for requesting a proposal from <strong>${companyName}</strong>. Based on your questionnaire answers, we have prepared a tailored marketing strategy and pricing quote.</p>
          
          <div style="background-color: #f8fafc; border-left: 4px solid #f57c00; padding: 12px; margin: 18px 0; border-radius: 4px;">
            <p style="margin: 0;"><strong>Quotation Number:</strong> #${quotation.quotationNumber}</p>
            <p style="margin: 4px 0 0 0;"><strong>Total Quote:</strong> ₹${Number(quotation.total).toLocaleString('en-IN')}</p>
          </div>

          <p>Please find the detailed PDF proposal attached to this email. It outlines the full scope of work, service details, timelines, and strategy recommendations generated by our AI system.</p>
          
          <p>If you have any questions or would like to customize these services further, please reply directly to this email or call us at <strong>+91 9240-203-227</strong>.</p>
          
          <p>We look forward to helping your business grow!</p>
          
          <p style="margin-top: 25px; border-top: 1px solid #f1f5f9; padding-top: 15px; font-size: 0.9em; color: #64748b;">
             Best regards,<br>
             <strong>StartupFlora Team</strong><br>
             info@startupflora.com
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `Quotation-${quotation.quotationNumber}.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf',
        },
      ],
    };

    // 3. Send email
    await transporter.sendMail(mailOptions);

    // 4. Update status to 'sent'
    await prisma.quotation.update({
      where: { id },
      data: { status: 'sent' },
    });

    return NextResponse.json({ message: 'Email sent successfully' });
  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
*/
